[package]
name = "coapum"
version = "0.2.0"
edition = "2024"
rust-version = "1.85.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["sled-observer"]
sled-observer = ["sled"]

[dependencies]
async-trait = "0.1.89"
ciborium = "0.2.2"
coap-lite = "0.13.3"
env_logger = "0.11.8"
futures = "0.3.31"
log = "0.4.27"
route-recognizer = "0.3.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.142"
tokio = { version = "1.47.1", features = ["full"] }
tower = { version = "0.5.2", features = [
    "tokio",
    "tokio-stream",
    "tokio-util",
] }

# Optional
sled = { version = "0.34.7", optional = true }

# DTLS
webrtc-dtls = { version = "0.12" }
webrtc-util = { version = "0.11" }

# SenML
coapum-senml = { path = "./coapum-senml" }


[dev-dependencies]
lazy_static = { version = "1.4.0" }
criterion = { version = "0.7.0" }

[[bench]]
name = "router_bench"
harness = false
