[package]
name = "coapum"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["sled-observer"]
sled-observer = ["sled"]

[dependencies]
async-trait = "0.1.68"
ciborium = "0.2.1"
coap-lite = "0.11.2"
env_logger = "0.10"
futures = "0.3.28"
log = "0.4"
route-recognizer = "0.3.1"
serde_json = "1.0.97"
tokio = { version = "1.29.1", features = ["full"] }
tower = { version = "0.4.13", features = [
    "tokio",
    "tokio-stream",
    "tokio-util",
] }
webrtc-dtls = { git = "https://github.com/jaredwolff/webrtc.git", branch = "jared/get-psk-identity" }
webrtc-util = { git = "https://github.com/jaredwolff/webrtc.git", branch = "jared/get-psk-identity" }

# Optional
sled = { version = "0.34.7", optional = true }

# webrtc-dtls = { path = "../webrtc/dtls" }
# webrtc-util = { path = "../webrtc/util" }

[dev-dependencies]
lazy_static = { version = "1.4.0" }
criterion = { version = "0.5.1" }

[[bench]]
name = "router_bench"
harness = false
