name: Bug Report
description: File a bug report to help us improve Coapum
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - maintainer-username

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 🐛

        Please search existing issues before creating a new one to avoid duplicates.

  - type: input
    id: version
    attributes:
      label: Coapum Version
      description: What version of Coapum are you using?
      placeholder: "0.2.0"
    validations:
      required: true

  - type: dropdown
    id: rust-version
    attributes:
      label: Rust Version
      description: What version of Rust are you using?
      options:
        - "1.75+ (latest stable)"
        - "1.70-1.74"
        - "Beta"
        - "Nightly"
        - "Other (specify in description)"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - "Linux"
        - "macOS"
        - "Windows"
        - "Other (specify in description)"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: "Describe the bug..."
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: "I expected..."
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: "Instead, what happened was..."
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Create a new project with `cargo new test-project`
        2. Add coapum dependency
        3. Run the following code:
        ```rust
        // Your code here
        ```
        4. See error
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Minimal Reproducible Example
      description: Please provide a minimal code example that reproduces the issue
      render: rust
      placeholder: |
        use coapum::*;

        #[tokio::main]
        async fn main() {
            // Your minimal example here
        }
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Error Messages / Logs
      description: Please copy and paste any relevant error messages or logs
      render: shell
      placeholder: |
        Error messages, stack traces, or log output here...
    validations:
      required: false

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - "Router"
        - "Handler/Extractors"
        - "Observer"
        - "DTLS/Security"
        - "Examples"
        - "Documentation"
        - "Build/Dependencies"
        - "Other"
    validations:
      required: false

  - type: checkboxes
    id: features
    attributes:
      label: Features Used
      description: Which features are you using? (Check all that apply)
      options:
        - label: "Default features"
        - label: "sled-observer"
        - label: "Custom features (specify in additional context)"

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: |
        Add any other context about the problem here.

        This could include:
        - Related issues
        - Workarounds you've tried
        - Impact on your project
        - Any other relevant information
      placeholder: "Any additional context..."
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: "I have searched existing issues to avoid creating duplicates"
          required: true
        - label: "I have provided a clear description of the bug"
          required: true
        - label: "I have included steps to reproduce the issue"
          required: true
        - label: "I am using a supported version of Rust (1.70+)"
          required: true
